name : CI

on : [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, xml, zip, curl
          coverage: none
          tools: composer

      - run : composer install
      - run: php bin/phpunit

  deploy:
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy on FTP
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.CD_HOST }}
          username: ${{ secrets.CD_USERNAME }}
          key: ${{ secrets.CD_PASSWORD }}
          script: |
            cd /var/www/myapp
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php bin/console cache:clear